// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/coredeno.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ModuleStatusResponse_Status int32

const (
	ModuleStatusResponse_UNKNOWN ModuleStatusResponse_Status = 0
	ModuleStatusResponse_LOADING ModuleStatusResponse_Status = 1
	ModuleStatusResponse_RUNNING ModuleStatusResponse_Status = 2
	ModuleStatusResponse_STOPPED ModuleStatusResponse_Status = 3
	ModuleStatusResponse_ERRORED ModuleStatusResponse_Status = 4
)

// Enum value maps for ModuleStatusResponse_Status.
var (
	ModuleStatusResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "LOADING",
		2: "RUNNING",
		3: "STOPPED",
		4: "ERRORED",
	}
	ModuleStatusResponse_Status_value = map[string]int32{
		"UNKNOWN": 0,
		"LOADING": 1,
		"RUNNING": 2,
		"STOPPED": 3,
		"ERRORED": 4,
	}
)

func (x ModuleStatusResponse_Status) Enum() *ModuleStatusResponse_Status {
	p := new(ModuleStatusResponse_Status)
	*p = x
	return p
}

func (x ModuleStatusResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModuleStatusResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_coredeno_proto_enumTypes[0].Descriptor()
}

func (ModuleStatusResponse_Status) Type() protoreflect.EnumType {
	return &file_proto_coredeno_proto_enumTypes[0]
}

func (x ModuleStatusResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModuleStatusResponse_Status.Descriptor instead.
func (ModuleStatusResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{24, 0}
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_coredeno_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_coredeno_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type FileReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ModuleCode    string                 `protobuf:"bytes,2,opt,name=module_code,json=moduleCode,proto3" json:"module_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadRequest) Reset() {
	*x = FileReadRequest{}
	mi := &file_proto_coredeno_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadRequest) ProtoMessage() {}

func (x *FileReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadRequest.ProtoReflect.Descriptor instead.
func (*FileReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{2}
}

func (x *FileReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileReadRequest) GetModuleCode() string {
	if x != nil {
		return x.ModuleCode
	}
	return ""
}

type FileReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileReadResponse) Reset() {
	*x = FileReadResponse{}
	mi := &file_proto_coredeno_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileReadResponse) ProtoMessage() {}

func (x *FileReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileReadResponse.ProtoReflect.Descriptor instead.
func (*FileReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{3}
}

func (x *FileReadResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type FileWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ModuleCode    string                 `protobuf:"bytes,3,opt,name=module_code,json=moduleCode,proto3" json:"module_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWriteRequest) Reset() {
	*x = FileWriteRequest{}
	mi := &file_proto_coredeno_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteRequest) ProtoMessage() {}

func (x *FileWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteRequest.ProtoReflect.Descriptor instead.
func (*FileWriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{4}
}

func (x *FileWriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileWriteRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *FileWriteRequest) GetModuleCode() string {
	if x != nil {
		return x.ModuleCode
	}
	return ""
}

type FileWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileWriteResponse) Reset() {
	*x = FileWriteResponse{}
	mi := &file_proto_coredeno_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileWriteResponse) ProtoMessage() {}

func (x *FileWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileWriteResponse.ProtoReflect.Descriptor instead.
func (*FileWriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{5}
}

func (x *FileWriteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type FileListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ModuleCode    string                 `protobuf:"bytes,2,opt,name=module_code,json=moduleCode,proto3" json:"module_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListRequest) Reset() {
	*x = FileListRequest{}
	mi := &file_proto_coredeno_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListRequest) ProtoMessage() {}

func (x *FileListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListRequest.ProtoReflect.Descriptor instead.
func (*FileListRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{6}
}

func (x *FileListRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileListRequest) GetModuleCode() string {
	if x != nil {
		return x.ModuleCode
	}
	return ""
}

type FileListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*FileEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileListResponse) Reset() {
	*x = FileListResponse{}
	mi := &file_proto_coredeno_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileListResponse) ProtoMessage() {}

func (x *FileListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileListResponse.ProtoReflect.Descriptor instead.
func (*FileListResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{7}
}

func (x *FileListResponse) GetEntries() []*FileEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type FileEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDir         bool                   `protobuf:"varint,2,opt,name=is_dir,json=isDir,proto3" json:"is_dir,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileEntry) Reset() {
	*x = FileEntry{}
	mi := &file_proto_coredeno_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileEntry) ProtoMessage() {}

func (x *FileEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileEntry.ProtoReflect.Descriptor instead.
func (*FileEntry) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{8}
}

func (x *FileEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FileEntry) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileEntry) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type FileDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	ModuleCode    string                 `protobuf:"bytes,2,opt,name=module_code,json=moduleCode,proto3" json:"module_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDeleteRequest) Reset() {
	*x = FileDeleteRequest{}
	mi := &file_proto_coredeno_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDeleteRequest) ProtoMessage() {}

func (x *FileDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDeleteRequest.ProtoReflect.Descriptor instead.
func (*FileDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{9}
}

func (x *FileDeleteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FileDeleteRequest) GetModuleCode() string {
	if x != nil {
		return x.ModuleCode
	}
	return ""
}

type FileDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileDeleteResponse) Reset() {
	*x = FileDeleteResponse{}
	mi := &file_proto_coredeno_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileDeleteResponse) ProtoMessage() {}

func (x *FileDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileDeleteResponse.ProtoReflect.Descriptor instead.
func (*FileDeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{10}
}

func (x *FileDeleteResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type StoreGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ModuleCode    string                 `protobuf:"bytes,3,opt,name=module_code,json=moduleCode,proto3" json:"module_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreGetRequest) Reset() {
	*x = StoreGetRequest{}
	mi := &file_proto_coredeno_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreGetRequest) ProtoMessage() {}

func (x *StoreGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreGetRequest.ProtoReflect.Descriptor instead.
func (*StoreGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{11}
}

func (x *StoreGetRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *StoreGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreGetRequest) GetModuleCode() string {
	if x != nil {
		return x.ModuleCode
	}
	return ""
}

type StoreGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreGetResponse) Reset() {
	*x = StoreGetResponse{}
	mi := &file_proto_coredeno_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreGetResponse) ProtoMessage() {}

func (x *StoreGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreGetResponse.ProtoReflect.Descriptor instead.
func (*StoreGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{12}
}

func (x *StoreGetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StoreGetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type StoreSetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         string                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	ModuleCode    string                 `protobuf:"bytes,4,opt,name=module_code,json=moduleCode,proto3" json:"module_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreSetRequest) Reset() {
	*x = StoreSetRequest{}
	mi := &file_proto_coredeno_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSetRequest) ProtoMessage() {}

func (x *StoreSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreSetRequest.ProtoReflect.Descriptor instead.
func (*StoreSetRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{13}
}

func (x *StoreSetRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *StoreSetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreSetRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StoreSetRequest) GetModuleCode() string {
	if x != nil {
		return x.ModuleCode
	}
	return ""
}

type StoreSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreSetResponse) Reset() {
	*x = StoreSetResponse{}
	mi := &file_proto_coredeno_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreSetResponse) ProtoMessage() {}

func (x *StoreSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreSetResponse.ProtoReflect.Descriptor instead.
func (*StoreSetResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{14}
}

func (x *StoreSetResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ProcessStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	ModuleCode    string                 `protobuf:"bytes,3,opt,name=module_code,json=moduleCode,proto3" json:"module_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessStartRequest) Reset() {
	*x = ProcessStartRequest{}
	mi := &file_proto_coredeno_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStartRequest) ProtoMessage() {}

func (x *ProcessStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStartRequest.ProtoReflect.Descriptor instead.
func (*ProcessStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{15}
}

func (x *ProcessStartRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *ProcessStartRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ProcessStartRequest) GetModuleCode() string {
	if x != nil {
		return x.ModuleCode
	}
	return ""
}

type ProcessStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessStartResponse) Reset() {
	*x = ProcessStartResponse{}
	mi := &file_proto_coredeno_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStartResponse) ProtoMessage() {}

func (x *ProcessStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStartResponse.ProtoReflect.Descriptor instead.
func (*ProcessStartResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{16}
}

func (x *ProcessStartResponse) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

type ProcessStopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	ModuleCode    string                 `protobuf:"bytes,2,opt,name=module_code,json=moduleCode,proto3" json:"module_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessStopRequest) Reset() {
	*x = ProcessStopRequest{}
	mi := &file_proto_coredeno_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStopRequest) ProtoMessage() {}

func (x *ProcessStopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStopRequest.ProtoReflect.Descriptor instead.
func (*ProcessStopRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{17}
}

func (x *ProcessStopRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *ProcessStopRequest) GetModuleCode() string {
	if x != nil {
		return x.ModuleCode
	}
	return ""
}

type ProcessStopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessStopResponse) Reset() {
	*x = ProcessStopResponse{}
	mi := &file_proto_coredeno_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStopResponse) ProtoMessage() {}

func (x *ProcessStopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStopResponse.ProtoReflect.Descriptor instead.
func (*ProcessStopResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{18}
}

func (x *ProcessStopResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type LoadModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	EntryPoint    string                 `protobuf:"bytes,2,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
	Permissions   []string               `protobuf:"bytes,3,rep,name=permissions,proto3" json:"permissions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModuleRequest) Reset() {
	*x = LoadModuleRequest{}
	mi := &file_proto_coredeno_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModuleRequest) ProtoMessage() {}

func (x *LoadModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModuleRequest.ProtoReflect.Descriptor instead.
func (*LoadModuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{19}
}

func (x *LoadModuleRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoadModuleRequest) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

func (x *LoadModuleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

type LoadModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadModuleResponse) Reset() {
	*x = LoadModuleResponse{}
	mi := &file_proto_coredeno_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadModuleResponse) ProtoMessage() {}

func (x *LoadModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadModuleResponse.ProtoReflect.Descriptor instead.
func (*LoadModuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{20}
}

func (x *LoadModuleResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LoadModuleResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type UnloadModuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModuleRequest) Reset() {
	*x = UnloadModuleRequest{}
	mi := &file_proto_coredeno_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModuleRequest) ProtoMessage() {}

func (x *UnloadModuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModuleRequest.ProtoReflect.Descriptor instead.
func (*UnloadModuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{21}
}

func (x *UnloadModuleRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type UnloadModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnloadModuleResponse) Reset() {
	*x = UnloadModuleResponse{}
	mi := &file_proto_coredeno_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnloadModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnloadModuleResponse) ProtoMessage() {}

func (x *UnloadModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnloadModuleResponse.ProtoReflect.Descriptor instead.
func (*UnloadModuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{22}
}

func (x *UnloadModuleResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type ModuleStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleStatusRequest) Reset() {
	*x = ModuleStatusRequest{}
	mi := &file_proto_coredeno_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleStatusRequest) ProtoMessage() {}

func (x *ModuleStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleStatusRequest.ProtoReflect.Descriptor instead.
func (*ModuleStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{23}
}

func (x *ModuleStatusRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type ModuleStatusResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Code          string                      `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        ModuleStatusResponse_Status `protobuf:"varint,2,opt,name=status,proto3,enum=coredeno.ModuleStatusResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleStatusResponse) Reset() {
	*x = ModuleStatusResponse{}
	mi := &file_proto_coredeno_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleStatusResponse) ProtoMessage() {}

func (x *ModuleStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coredeno_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleStatusResponse.ProtoReflect.Descriptor instead.
func (*ModuleStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_coredeno_proto_rawDescGZIP(), []int{24}
}

func (x *ModuleStatusResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ModuleStatusResponse) GetStatus() ModuleStatusResponse_Status {
	if x != nil {
		return x.Status
	}
	return ModuleStatusResponse_UNKNOWN
}

var File_proto_coredeno_proto protoreflect.FileDescriptor

const file_proto_coredeno_proto_rawDesc = "" +
	"\n" +
	"\x14proto/coredeno.proto\x12\bcoredeno\"\r\n" +
	"\vPingRequest\"\x1e\n" +
	"\fPingResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"F\n" +
	"\x0fFileReadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vmodule_code\x18\x02 \x01(\tR\n" +
	"moduleCode\",\n" +
	"\x10FileReadResponse\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\"a\n" +
	"\x10FileWriteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1f\n" +
	"\vmodule_code\x18\x03 \x01(\tR\n" +
	"moduleCode\"#\n" +
	"\x11FileWriteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"F\n" +
	"\x0fFileListRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vmodule_code\x18\x02 \x01(\tR\n" +
	"moduleCode\"A\n" +
	"\x10FileListResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.coredeno.FileEntryR\aentries\"J\n" +
	"\tFileEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06is_dir\x18\x02 \x01(\bR\x05isDir\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\"H\n" +
	"\x11FileDeleteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1f\n" +
	"\vmodule_code\x18\x02 \x01(\tR\n" +
	"moduleCode\"$\n" +
	"\x12FileDeleteResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"Z\n" +
	"\x0fStoreGetRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x1f\n" +
	"\vmodule_code\x18\x03 \x01(\tR\n" +
	"moduleCode\">\n" +
	"\x10StoreGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"p\n" +
	"\x0fStoreSetRequest\x12\x14\n" +
	"\x05group\x18\x01 \x01(\tR\x05group\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1f\n" +
	"\vmodule_code\x18\x04 \x01(\tR\n" +
	"moduleCode\"\"\n" +
	"\x10StoreSetResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"d\n" +
	"\x13ProcessStartRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x1f\n" +
	"\vmodule_code\x18\x03 \x01(\tR\n" +
	"moduleCode\"5\n" +
	"\x14ProcessStartResponse\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\"T\n" +
	"\x12ProcessStopRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12\x1f\n" +
	"\vmodule_code\x18\x02 \x01(\tR\n" +
	"moduleCode\"%\n" +
	"\x13ProcessStopResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"j\n" +
	"\x11LoadModuleRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1f\n" +
	"\ventry_point\x18\x02 \x01(\tR\n" +
	"entryPoint\x12 \n" +
	"\vpermissions\x18\x03 \x03(\tR\vpermissions\":\n" +
	"\x12LoadModuleResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\")\n" +
	"\x13UnloadModuleRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"&\n" +
	"\x14UnloadModuleResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\")\n" +
	"\x13ModuleStatusRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\"\xb4\x01\n" +
	"\x14ModuleStatusResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12=\n" +
	"\x06status\x18\x02 \x01(\x0e2%.coredeno.ModuleStatusResponse.StatusR\x06status\"I\n" +
	"\x06Status\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aLOADING\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\v\n" +
	"\aSTOPPED\x10\x03\x12\v\n" +
	"\aERRORED\x10\x042\xfa\x04\n" +
	"\vCoreService\x125\n" +
	"\x04Ping\x12\x15.coredeno.PingRequest\x1a\x16.coredeno.PingResponse\x12A\n" +
	"\bFileRead\x12\x19.coredeno.FileReadRequest\x1a\x1a.coredeno.FileReadResponse\x12D\n" +
	"\tFileWrite\x12\x1a.coredeno.FileWriteRequest\x1a\x1b.coredeno.FileWriteResponse\x12A\n" +
	"\bFileList\x12\x19.coredeno.FileListRequest\x1a\x1a.coredeno.FileListResponse\x12G\n" +
	"\n" +
	"FileDelete\x12\x1b.coredeno.FileDeleteRequest\x1a\x1c.coredeno.FileDeleteResponse\x12A\n" +
	"\bStoreGet\x12\x19.coredeno.StoreGetRequest\x1a\x1a.coredeno.StoreGetResponse\x12A\n" +
	"\bStoreSet\x12\x19.coredeno.StoreSetRequest\x1a\x1a.coredeno.StoreSetResponse\x12M\n" +
	"\fProcessStart\x12\x1d.coredeno.ProcessStartRequest\x1a\x1e.coredeno.ProcessStartResponse\x12J\n" +
	"\vProcessStop\x12\x1c.coredeno.ProcessStopRequest\x1a\x1d.coredeno.ProcessStopResponse2\xf4\x01\n" +
	"\vDenoService\x12G\n" +
	"\n" +
	"LoadModule\x12\x1b.coredeno.LoadModuleRequest\x1a\x1c.coredeno.LoadModuleResponse\x12M\n" +
	"\fUnloadModule\x12\x1d.coredeno.UnloadModuleRequest\x1a\x1e.coredeno.UnloadModuleResponse\x12M\n" +
	"\fModuleStatus\x12\x1d.coredeno.ModuleStatusRequest\x1a\x1e.coredeno.ModuleStatusResponseB\x1cZ\x1adappco.re/go/core/ts/protob\x06proto3"

var (
	file_proto_coredeno_proto_rawDescOnce sync.Once
	file_proto_coredeno_proto_rawDescData []byte
)

func file_proto_coredeno_proto_rawDescGZIP() []byte {
	file_proto_coredeno_proto_rawDescOnce.Do(func() {
		file_proto_coredeno_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coredeno_proto_rawDesc), len(file_proto_coredeno_proto_rawDesc)))
	})
	return file_proto_coredeno_proto_rawDescData
}

var file_proto_coredeno_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_coredeno_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_coredeno_proto_goTypes = []any{
	(ModuleStatusResponse_Status)(0), // 0: coredeno.ModuleStatusResponse.Status
	(*PingRequest)(nil),              // 1: coredeno.PingRequest
	(*PingResponse)(nil),             // 2: coredeno.PingResponse
	(*FileReadRequest)(nil),          // 3: coredeno.FileReadRequest
	(*FileReadResponse)(nil),         // 4: coredeno.FileReadResponse
	(*FileWriteRequest)(nil),         // 5: coredeno.FileWriteRequest
	(*FileWriteResponse)(nil),        // 6: coredeno.FileWriteResponse
	(*FileListRequest)(nil),          // 7: coredeno.FileListRequest
	(*FileListResponse)(nil),         // 8: coredeno.FileListResponse
	(*FileEntry)(nil),                // 9: coredeno.FileEntry
	(*FileDeleteRequest)(nil),        // 10: coredeno.FileDeleteRequest
	(*FileDeleteResponse)(nil),       // 11: coredeno.FileDeleteResponse
	(*StoreGetRequest)(nil),          // 12: coredeno.StoreGetRequest
	(*StoreGetResponse)(nil),         // 13: coredeno.StoreGetResponse
	(*StoreSetRequest)(nil),          // 14: coredeno.StoreSetRequest
	(*StoreSetResponse)(nil),         // 15: coredeno.StoreSetResponse
	(*ProcessStartRequest)(nil),      // 16: coredeno.ProcessStartRequest
	(*ProcessStartResponse)(nil),     // 17: coredeno.ProcessStartResponse
	(*ProcessStopRequest)(nil),       // 18: coredeno.ProcessStopRequest
	(*ProcessStopResponse)(nil),      // 19: coredeno.ProcessStopResponse
	(*LoadModuleRequest)(nil),        // 20: coredeno.LoadModuleRequest
	(*LoadModuleResponse)(nil),       // 21: coredeno.LoadModuleResponse
	(*UnloadModuleRequest)(nil),      // 22: coredeno.UnloadModuleRequest
	(*UnloadModuleResponse)(nil),     // 23: coredeno.UnloadModuleResponse
	(*ModuleStatusRequest)(nil),      // 24: coredeno.ModuleStatusRequest
	(*ModuleStatusResponse)(nil),     // 25: coredeno.ModuleStatusResponse
}
var file_proto_coredeno_proto_depIdxs = []int32{
	9,  // 0: coredeno.FileListResponse.entries:type_name -> coredeno.FileEntry
	0,  // 1: coredeno.ModuleStatusResponse.status:type_name -> coredeno.ModuleStatusResponse.Status
	1,  // 2: coredeno.CoreService.Ping:input_type -> coredeno.PingRequest
	3,  // 3: coredeno.CoreService.FileRead:input_type -> coredeno.FileReadRequest
	5,  // 4: coredeno.CoreService.FileWrite:input_type -> coredeno.FileWriteRequest
	7,  // 5: coredeno.CoreService.FileList:input_type -> coredeno.FileListRequest
	10, // 6: coredeno.CoreService.FileDelete:input_type -> coredeno.FileDeleteRequest
	12, // 7: coredeno.CoreService.StoreGet:input_type -> coredeno.StoreGetRequest
	14, // 8: coredeno.CoreService.StoreSet:input_type -> coredeno.StoreSetRequest
	16, // 9: coredeno.CoreService.ProcessStart:input_type -> coredeno.ProcessStartRequest
	18, // 10: coredeno.CoreService.ProcessStop:input_type -> coredeno.ProcessStopRequest
	20, // 11: coredeno.DenoService.LoadModule:input_type -> coredeno.LoadModuleRequest
	22, // 12: coredeno.DenoService.UnloadModule:input_type -> coredeno.UnloadModuleRequest
	24, // 13: coredeno.DenoService.ModuleStatus:input_type -> coredeno.ModuleStatusRequest
	2,  // 14: coredeno.CoreService.Ping:output_type -> coredeno.PingResponse
	4,  // 15: coredeno.CoreService.FileRead:output_type -> coredeno.FileReadResponse
	6,  // 16: coredeno.CoreService.FileWrite:output_type -> coredeno.FileWriteResponse
	8,  // 17: coredeno.CoreService.FileList:output_type -> coredeno.FileListResponse
	11, // 18: coredeno.CoreService.FileDelete:output_type -> coredeno.FileDeleteResponse
	13, // 19: coredeno.CoreService.StoreGet:output_type -> coredeno.StoreGetResponse
	15, // 20: coredeno.CoreService.StoreSet:output_type -> coredeno.StoreSetResponse
	17, // 21: coredeno.CoreService.ProcessStart:output_type -> coredeno.ProcessStartResponse
	19, // 22: coredeno.CoreService.ProcessStop:output_type -> coredeno.ProcessStopResponse
	21, // 23: coredeno.DenoService.LoadModule:output_type -> coredeno.LoadModuleResponse
	23, // 24: coredeno.DenoService.UnloadModule:output_type -> coredeno.UnloadModuleResponse
	25, // 25: coredeno.DenoService.ModuleStatus:output_type -> coredeno.ModuleStatusResponse
	14, // [14:26] is the sub-list for method output_type
	2,  // [2:14] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_coredeno_proto_init() }
func file_proto_coredeno_proto_init() {
	if File_proto_coredeno_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coredeno_proto_rawDesc), len(file_proto_coredeno_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_coredeno_proto_goTypes,
		DependencyIndexes: file_proto_coredeno_proto_depIdxs,
		EnumInfos:         file_proto_coredeno_proto_enumTypes,
		MessageInfos:      file_proto_coredeno_proto_msgTypes,
	}.Build()
	File_proto_coredeno_proto = out.File
	file_proto_coredeno_proto_goTypes = nil
	file_proto_coredeno_proto_depIdxs = nil
}
